export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_FAILED = 'REQUEST_EVENTS_FAILED';

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';

export const POST_EVENT_SUCCESS = 'POST_EVENT_SUCCESS';
